name: Release Beet project

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install Poppler
      run: |
        sudo apt-get update
        sudo apt-get install poppler-utils

    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Build Beet project
      id: beet
      uses: Trioplane/action-build-beet-project@v1

    - name: Zip build output
      run: |
        echo '${{ steps.beet.outputs.data-packs }}' | jq -r '.[]' | while read dir; do
          name=$(basename "$dir")
          (cd "$dir" && zip -r "${GITHUB_WORKSPACE}/${name}.zip" .)
        done
          
        echo '${{ steps.beet.outputs.resource-packs }}' | jq -r '.[]' | while read dir; do
          name=$(basename "$dir")
          (cd "$dir" && zip -r "${GITHUB_WORKSPACE}/${name}.zip" .)
        done

    - name: Get version from tag
      id: tag_name
      run: |
        echo "current_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: ${{ steps.tag_name.outputs.current_version }}
        path: ./CHANGELOG.md
          
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: "*.zip"
        body: ${{ steps.changelog_reader.outputs.changes }}

    - name: Create Modrinth Release
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: v1RI6iRt
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        files: "*.zip"
        name: "${{ steps.beet.outputs.name }} ${{ steps.beet.outputs.version }}"
        version: ${{ steps.beet.outputs.version }}
        loaders: |
          minecraft
        changelog: ${{ steps.changelog_reader.outputs.changes }}